version: '3.9'

services:
  zookeeper:
    env_file:
      - .env.testing

  kafka:
    env_file:
      - .env.testing

  postgres:
    env_file:
      - .env.testing
    volumes:
      - ./pg_data_test:/var/lib/postgresql/data

volumes:
  pg_data_test:
