version: '3.9'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - '2181:2181'
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    networks:
      - app_network

  kafka:
    image: bitnami/kafka:latest
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_MESSAGE_MAX_BYTES: 10000
    depends_on:
      - zookeeper
    networks:
      - app_network

  postgres:
    image: postgres:15.3
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}'
    depends_on:
      - postgres
      - kafka

    networks:
      - app_network
    profiles:
      - production
      - staging
      - development

volumes:
  pg_data:

networks:
  app_network:
    driver: bridge
