version: '3.9'

services:
  zookeeper:
    env_file:
      - .env.staging

  kafka:
    env_file:
      - .env.staging

  postgres:
    env_file:
      - .env.staging
    volumes:
      - ./pg_data_stage:/var/lib/postgresql/data

  app:
    env_file:
      - .env.staging
    command:
      [
        '/bin/bash',
        '-c',
        '/app/wait-for-it.sh --timeout=30 --strict postgres:$$POSTGRES_PORT && sleep 10 && npx node-pg-migrate up && yarn build && yarn start:stage',
      ]

volumes:
  pg_data_stage:
