version: '3.9'

services:
  zookeeper:
    env_file:
      - .env.local

  kafka:
    env_file:
      - .env.local

  postgres:
    env_file:
      - .env.local
    volumes:
      - ./pg_data_local:/var/lib/postgresql/data

volumes:
  pg_data_local:
